# from https://docs.travis-ci.com/user/languages/android/
language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
  - tools
  - platform-tools
    # The SDK version used to compile your project
  - android-25

# caching from https://stackoverflow.com/a/38772440
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
  - TRAVIS_SDK_PATH=/usr/local/android-sdk/licenses
  - secure: "Na7QEyUACs6m4mubocccHnGAyeAuEZHgnMB3OvB2Mur0kQQ68S7OUWWm16s4meEeVZnMBhUHb1tqamJDeKXTTKkPBVNA4UZhs/eFcftBBrQFAJA6HhKbdqwO+fEHJIaoa8Sa09z8QLmS9BhkB3a+/UvAkLeFsBPf5K3p6p1PKpSK7wNT6RoLN5kOWrlJoKYPexl1oXcu7zTz4/nSpr4M4WdTUoM1rM/4X1KDxeUQ0RDxwY4NP/6g+BVifXHOSKsQNpf0pkPzSIinuKr36n2BhjEQxuaHFTAamJArIcAhjt3xbY7OnCmOaaOe7UqaOPp2mR2HbcWov7GJqiyYuwWx+PCoQ1KhtPBgvFnpOlBmLhqlID+9c1gsQ8antoHApQmnhUKD2Osu+WAYk6P1mV27T6ysgpCGqHUNH20prsxovdnM6Zx2yTRwuD1UzUGl++B0i5LwCVuwqKqZHe0USH80ImPSxS2ztlaIxIEDHrYn5HoKv/vhr8mJtrfwtXXFp2OhEUfSWCF3IwRgJbnT4laoCDyBwKKXbiOc22cAOsMQ1yuLsGVD/4Yt/Gm5UcyOIM1JMCARQ7Q48gEcQR4u928S3g/1OdvfxTkVbFgqEhewNmYOkrF8QSCrMYVx//wJeZMgzBIOwl+dAOkojpaIDgFMLHn0pDF6fkUVIFeCqQtEiHw=" # TRANSIFEX_PASSWORD

before_script:
# install sdkman from https://sdkman.io/
- curl -s "https://get.sdkman.io" | bash && source /home/travis/.sdkman/bin/sdkman-init.sh
# install gradle of a specific version, from https://gradle.org/install/#with-a-package-manager
- sdk install gradle 4.4
# install the licenses
- mkdir -p "$TRAVIS_SDK_PATH" && cp .travis/licenses.zip "$TRAVIS_SDK_PATH" && ( cd "$TRAVIS_SDK_PATH" && unzip licenses.zip && rm licenses.zip )
- .travis/prepare-transifex.sh

script:
- tx pull --all
- gradle build
- "find | grep '\\.apk'"
- .travis/release-apk && [ -f "`.travis/release-apk`" ]
- .travis/debug-apk && [ -f "`.travis/debug-apk`" ]

before_deploy:
- .travis/create_tag
- cp "`.travis/release-apk`" mundraub-release-unsigned.apk
- cp "`.travis/debug-apk`" mundraub-debug.apk

deploy:
  - provider: script
    script: tx push --source
    skip_cleanup: true
    on:
      branch: master
  - provider: releases
    api_key:
      secure: bvhMN07c2vgCBTH62fiF+XwK/4Vs0n6kIwP3Fv+emWgu7TUtEgn8Ypx2Bft3nKYZCZJa2/nM5BBqJ4OanSAzhiLT5u8PT6tbPAJRxe98mUYR090aUReHEUesWKuwFVvhpjp0G1obY7p2YrnxjugJrrr/rgr8Rps382h3kKws9cTyWg1vYlbvmzH2Ks//7lObU3UiGit61La4VYffkcYOEYCo4UQQsrCScnHokYmf9sorimNTSFBQvuaLZpJF91T++Xa2Bl5IsbGnE0gQ3bGEltmKKbukkvGCsmKjxNj3WMIoPfjZfF1D6P9koiWXGMncex4dsdAU3nGGfeyAJpNlQMsCHMEu+Phu7qZsaLJHeo1LIFrkRnkBegNxOWjP8VW9+cMvAwuCfwkJMqPJZRcBUy3RoBRgoXha1jaLTb4LMxLO+WSd4Qf1X5zw437XSiKHRnXc+8noKbvSknTsc4MygyO84chuvbX/i9qNpVGiWRXfnnMCZlGStvY0O8Aov+19wohM1crvaTaA1fZezJjjOCXE004tjjPMUw2plJccn7OVjb/K4F7WkZclbF+yJujOaeX3oYxpgZEsPb7dgyuIB7pGq40kJ8tJLbZaDaHteHvSYpfsFsrbK4B3fCHt3FOgjeA9oj+U9vwpF27GDgvs2XYPCM20W9UpZdFJljYokNw=
    file:
    - mundraub-debug.apk
    - mundraub-release-unsigned.apk
    skip_cleanup: true
    on:
      repo: niccokunzmann/mundraub-android

